----------------TLB_ROL----------------------Funciona

CREATE SEQUENCE ROL_SEQ START WITH 1; 

CREATE OR REPLACE TRIGGER ROL_BIR
BEFORE INSERT ON TBL_ROLES
FOR EACH ROW

BEGIN 
  SELECT ROL_SEQ.NEXTVAL
  INTO :NEW.ID_ROL
  FROM DUAL;
END;

---------------TBL_DISTRIBUIDOR---------------------Funciona

CREATE SEQUENCE DISTRIBUIDOR_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER DISTRIBUIDOR_BIR
BEFORE INSERT ON TBL_DISTRIBUIDOR
FOR EACH ROW
BEGIN 
  SELECT DISTRIBUIDOR_SEQ.NEXTVAL
  INTO :NEW.ID_DISTRIBUIDOR
  FROM DUAL;
END;

----------------TBL_FLORES----------------------------Funciona

CREATE SEQUENCE FLORES_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER FLORES_BIR
BEFORE INSERT ON TBL_FLORES
FOR EACH ROW
BEGIN 
  SELECT FLORES_SEQ.NEXTVAL
  INTO :NEW.ID_FLOR 
  FROM DUAL;
END;

--INSERT INTO TBL_FLORES (NOMBRE, TIPO, DETALLE) VALUES ('ROSA','PLANTA','ROSA ROSA ROJA');


--------------TBL_INVENTARIOS-------------------------FUNCIONA

CREATE SEQUENCE INVENTARIOS_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER INVENTARIOS_BIR
BEFORE INSERT ON TBL_INVENTARIOS
FOR EACH ROW
BEGIN 
  SELECT INVENTARIOS_SEQ.NEXTVAL
  INTO :NEW.ID_INVENTARIO
  FROM DUAL;
END;

--INSERT INTO TBL_INVENTARIOS (ID_FLOR, VIDA_UTIL, CANTIDAD_ROLLOS, FECHA_CORTE, ESTADO) VALUES (2,'30 DIAS',50,'12/12/12','BUENAS'); 

-------------TBL_PEDIDOS------------------------------------------FUNCIONA

CREATE SEQUENCE PEDIDOS_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER PEDIDOS_BIR
BEFORE INSERT ON TBL_PEDIDOS
FOR EACH ROW
BEGIN 
  SELECT PEDIDOS_SEQ.NEXTVAL
  INTO :NEW.ID_PEDIDO
  FROM DUAL;
END;

-----------TBL_USUARIOS-----------------------------------------------funciona

CREATE SEQUENCE USUARIOS_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER USUARIOS_BIR
BEFORE INSERT ON TBL_USUARIOS
FOR EACH ROW
BEGIN 
  SELECT USUARIOS_SEQ.NEXTVAL
  INTO :NEW.ID_USUARIO
  FROM DUAL;
END;


------------TBL_VENTAS---------------------------------------------------funciona

CREATE SEQUENCE VENTAS_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER VENTAS_BIR
BEFORE INSERT ON TBL_VENTAS
FOR EACH ROW
BEGIN 
  SELECT VENTAS_SEQ.NEXTVAL
  INTO :NEW.ID_VENTAS
  FROM DUAL;
END;


------------------------------------------------------------------------
