
---------TBL_ROLES--------------

--ELIMINAR
create or replace 
PROCEDURE ELIMINAR_ROL(VID NUMBER)
AS 
BEGIN
 DELETE FROM TBL_ROLES WHERE ID_ROL=VID; 
 COMMIT;
END;

--ACTUALIZAR
create or replace 
PROCEDURE ACTUALIZAR_ROL(ROL NUMBER, VNOM VARCHAR2)
AS 
BEGIN
 UPDATE TBL_ROLES SET NOMBRE=VNOM WHERE ID_ROL = ROL;
 COMMIT;
END;

--INSERTAR
create or replace 
PROCEDURE INSERTAR_ROL(VNOMBRE VARCHAR2)
AS
BEGIN 
  INSERT INTO TBL_ROLES (NOMBRE) VALUES (VNOMBRE);
  COMMIT;
END;

-------FIN TBL_ROLES---------------------

--------TBL_DISTRIBUIDORES---------------

--ELIMINAR
create or replace 
PROCEDURE ELIMINAR_DISTRIBUIDOR(VID NUMBER)
AS 
BEGIN
 DELETE FROM TBL_DISTRIBUIDOR WHERE ID_DISTRIBUIDOR=VID; 
 COMMIT;
END;

--ACTUALIZAR
create or replace 
PROCEDURE ACTUALIZAR_DISTRIBUIDOR(VID NUMBER, VNOM VARCHAR2, VAPE VARCHAR2, VDIREC VARCHAR2, VTELE NUMBER)
AS 
BEGIN
 UPDATE TBL_DISTRIBUIDOR SET NOMBRE=VNOM, APELLIDO=VAPE, DIRECCION=VDIREC, TELEFONO=VTELE WHERE ID_DISTRIBUIDOR = VID;
 COMMIT;
END;

--INSERTAR
create or replace 
PROCEDURE INSERTAR_DISTRIBUIDOR(VNOM VARCHAR2, VAPE VARCHAR2, VDIREC VARCHAR2, VTELE NUMBER)
AS
BEGIN 
  INSERT INTO TBL_DISTRIBUIDOR (NOMBRE, APELLIDO, DIRECCION, TELEFONO) VALUES (VNOM, VAPE, VDIREC, VTELE);
  COMMIT;
END;
--------FIN TBL_DISTRIBUIDORES-----------

--------TBL_FLORES---------------FALTA DE REVISAR

--ELIMINAR
create or replace 
PROCEDURE ELIMINAR_FLORES(VID NUMBER)
AS 
BEGIN
 DELETE FROM TBL_FLORES WHERE ID_FLOR=VID; 
 COMMIT;
END;

--ACTUALIZAR
create or replace 
PROCEDURE ACTUALIZAR_FLORES(VID NUMBER, VNOM VARCHAR2, VTIPO VARCHAR2, VDETA VARCHAR2)
AS 
BEGIN
 UPDATE TBL_FLORES SET NOMBRE=VNOM, TIPO=VTIPO, DETALLE=VDETA WHERE ID_FLOR = VID;
 COMMIT;
END;

--INSERTAR
create or replace 
PROCEDURE INSERTAR_FLORES(VNOM VARCHAR2, VTIPO VARCHAR2, VDETA VARCHAR2)
AS
BEGIN 
  INSERT INTO TBL_FLORES (NOMBRE, TIPO, DETALLE) VALUES (VNOM, VTIPO, VDETA);
  COMMIT;
END;

--------FIN TBL_FLORES-----------

--------TBL_INVENTARIOS---------------funciona

--ELIMINAR
create or replace 
PROCEDURE ELIMINAR_INVENTARIO(VID NUMBER)
AS 
BEGIN
 DELETE FROM TBL_INVENTARIOS WHERE ID_INVENTARIO=VID; 
 COMMIT;
END;

--ACTUALIZAR
create or replace 
PROCEDURE ACTUALIZAR_INVENTARIO(VID NUMBER, VFLOR NUMBER, VVIDA_UTIL VARCHAR2, VCANT NUMBER, VFECHA_CORTE DATE, VESTADO VARCHAR2)
AS 
BEGIN
 UPDATE TBL_INVENTARIOS SET ID_FLOR=VFLOR, VIDA_UTIL=VVIDA_UTIL, CANTIDAD_ROLLOS=VCANT, FECHA_CORTE=VFECHA_CORTE, ESTADO=VESTADO WHERE ID_INVENTARIO = VID;
 COMMIT;
END;

--INSERTAR
create or replace 
PROCEDURE INSERTAR_INVENTARIO(VFLOR NUMBER, VVIDA_UTIL VARCHAR2, VCANT NUMBER, VFECHA_CORTE DATE, VESTADO VARCHAR2)
AS
BEGIN 
  INSERT INTO TBL_INVENTARIOS (ID_FLOR, VIDA_UTIL, CANTIDAD_ROLLOS, FECHA_CORTE, ESTADO) VALUES (VFLOR, VVIDA_UTIL, VCANT, VFECHA_CORTE, VESTADO);
  COMMIT;
END;

--------FIN TBL_INVENTARIOS-----------

--------TBL_PEDIDOS---------------FUNCIONES

--ELIMINAR
create or replace 
PROCEDURE ELIMINAR_PEDIDOS(VID NUMBER)
AS 
BEGIN
 DELETE FROM TBL_PEDIDOS WHERE ID_PEDIDO=VID; 
 COMMIT;
END;

--ACTUALIZAR
create or replace 
PROCEDURE ACTUALIZAR_PEDIDOS(VID NUMBER, VFLOR NUMBER, VCANT NUMBER, VFECHA_ENTREGA DATE, VFECHA_PEDIDO DATE)
AS 
BEGIN
 UPDATE TBL_PEDIDOS SET ID_FLOR=VFLOR, CANTIDAD=VCANT, FECHA_ENTREGA=VFECHA_ENTREGA, FECHA_PEDIDO=VFECHA_PEDIDO WHERE ID_PEDIDO = VID;
 COMMIT;
END;

--INSERTAR
create or replace 
PROCEDURE INSERTAR_PEDIDOS(VFLOR NUMBER, VCANT NUMBER, VFECHA_ENTREGA DATE, VFECHA_PEDIDO DATE)
AS
BEGIN 
  INSERT INTO TBL_PEDIDOS (ID_FLOR, CANTIDAD, FECHA_ENTREGA, FECHA_PEDIDO) VALUES (VFLOR, VCANT, VFECHA_ENTREGA, VFECHA_PEDIDO );
  COMMIT;
END;

--------FIN TBL_PEDIDOS-----------


-------TBL_USUARIOS---------------FUNCIONA

--ELIMINAR
create or replace 
PROCEDURE ELIMINAR_USUARIO(VID NUMBER)
AS 
BEGIN
 DELETE FROM TBL_USUARIOS WHERE ID_USUARIO=VID; 
 COMMIT;
END;

--ACTUALIZAR
create or replace 
PROCEDURE ACTUALIZAR_USUARIO(VID NUMBER, VROL NUMBER, VNOM VARCHAR2, VAPE VARCHAR2, VUSUARIO VARCHAR2, VPASS VARCHAR2)
AS 
BEGIN
 UPDATE TBL_USUARIOS SET ID_ROL=VROL, NOMBRE=VNOM, APELLIDO=VAPE, NOMBRE_USUARIO=VUSUARIO, CONTRASEÑA=VPASS WHERE ID_USUARIO = VID;
 COMMIT;
END;

--INSERTAR
create or replace 
PROCEDURE INSERTAR_USUARIO(VROL NUMBER, VNOM VARCHAR2, VAPE VARCHAR2, VUSUARIO VARCHAR2, VPASS VARCHAR2)
AS
BEGIN 
  INSERT INTO TBL_USUARIOS (ID_ROL, NOMBRE, APELLIDO, NOMBRE_USUARIO, CONTRASEÑA) VALUES (VROL, VNOM, VAPE, VUSUARIO, VPASS);
  COMMIT;
END;

------FIN TBL_USUARIOS------------

------TBL_VENTAS------------------

--ELIMINAR
create or replace 
PROCEDURE ELIMINAR_VENTAS(VID NUMBER)
AS 
BEGIN
 DELETE FROM TBL_VENTAS WHERE ID_VENTAS=VID; 
 COMMIT;
END;

--ACTUALIZAR
create or replace 
PROCEDURE ACTUALIZAR_VENTAS(VID NUMBER, VFLOR NUMBER, VUSUARIO NUMBER, VCLIENTE VARCHAR2, VCANT NUMBER, VFECHA_VENTA DATE)
AS 
BEGIN
 UPDATE TBL_VENTAS SET ID_VENTAS=VFLOR, ID_USUARIO=VUSUARIO, NOMBRE_CLIENTE=VCLIENTE, CANTIDAD=VCANT, FECHA_VENTA=VFECHA_VENTA WHERE ID_VENTAS = VID;
 COMMIT;
END;

--INSERTAR
create or replace 
PROCEDURE INSERTAR_VENTAS(VFLOR NUMBER, VUSUARIO NUMBER, VCLIENTE VARCHAR2, VCANT NUMBER, VFECHA_VENTA DATE)
AS
BEGIN 
  INSERT INTO TBL_VENTAS (ID_FLOR, ID_USUARIO, NOMBRE_CLIENTE, CANTIDAD, FECHA_VENTA) VALUES (VFLOR, VUSUARIO, VCLIENTE, VCANT, VFECHA_VENTA);
  COMMIT;
END;

----revisar la foreign key id_flor, no se puede cambiar y no sé por que, pero la pude borrar, extraño 

------FIN DE TBL_VENTAS-----------





