

CREATE VIEW FLOR_VENTAS AS SELECT F.NOMBRE, SUM(V.CANTIDAD) CANTIDAD FROM 
TBL_FLORES F, TBL_VENTAS V
WHERE  F.ID_FLOR=V.ID_FLOR
GROUP BY F.NOMBRE
ORDER BY SUM(V.CANTIDAD) DESC;

CREATE VIEW USUARIO_CANTIDAD_VENTAS AS SELECT U.NOMBRE,COUNT(ID_VENTAS) CANTIDAD FROM 
TBL_USUARIOS U, TBL_VENTAS V
WHERE U.ID_USUARIO=V.ID_USUARIO
GROUP BY U.NOMBRE
ORDER BY COUNT(ID_VENTAS) DESC;

CREATE VIEW FECHA_NUMERO_VENTAS AS SELECT FECHA_VENTA,COUNT(ID_VENTAS) NUMERO_VENTAS
FROM TBL_VENTAS
GROUP BY FECHA_VENTA
ORDER BY NUMERO_VENTAS DESC;



















